# fly.toml app configuration file generated for trading-assistant on 2025-11-01T00:48:58+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trading-assistant'
primary_region = 'bom'

[build]

[env]
  PORT = '8000'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
